name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Install PM2
        run: npm install -g pm2

      - name: Build the project
        run: npm run build
      # start / restart
      - name: Check if process exists and start/restart
        run: |
          if pm2 describe nextjs-app > /dev/null; then
            pm2 restart nextjs-app
          else
            pm2 start npm --name "nextjs-app" -- run start
          fi
